alias gb='git branch'¬
alias gd='git diff'¬
alias gcheckd='git checkout development'¬
alias gcheckm='git checkout master'¬
alias gs='git status'¬
alias gpul='git pull'¬
alias gpus='git push'¬
alias gl='git log'
alias e='exit'
